title: Hi, I'm Lauren Spann!
description: This is my technical writing portfolio.
Logo: https://github.com/lmspann/lmspann.github.io/blob/main/Assets/Img/lmspann.png
show_downloads: true
google_analytics: 
theme: jekyll-theme-minimal