title: Lauren Spann
description: Lauren Spann is an ERP solution implementation professional with five years of large scale SAP product implementation project experience at Deloitte Consulting.  
show_downloads: true
google_analytics: 
theme: jekyll-theme-modernist