title: Hi, I'm Lauren Spann!
logo: Assets/Img/lmspann.png
description: [LinkedIn](www.linkedin.com/in/lauren-spann-083055150), [Creative Writing](https://www.lmspann.com/)
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal